Controllers/VoituresController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet5ApplicationDotNet.Data;
using Projet5ApplicationDotNet.Models;
using Microsoft.AspNetCore.Authorization;

namespace Projet5ApplicationDotNet.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Voitures
        public async Task<IActionResult> Index()
        {
            // Liste des voitures disponibles pour les visiteurs
            var voitures = await _context.Voitures
                .Where(v => v.Disponible.Equals(true))
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .ToListAsync();

            // Sinon liste de toutes les voitures pour le vendeur
            if (User.IsInRole("ADMIN"))
            { 
                voitures = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .ToListAsync();

            }
            var VoitureViewModel = voitures.Select(v => new VoitureViewModel
            {
                IdVoiture = v.Id,
                CodeVIN = v.CodeVIN,
                DateAchat = v.DateAchat,
                Disponible = v.Disponible,
                DateVente = v.DateVente,
                PrixVente = v.PrixVente,
                Description = v.Description,
                Annee = v.UnModele.Annee,
                Marque = v.UnModele.UneMarque.Nom,
                Modele = v.UnModele.Nom,
                Finition = v.Finition,
                PhotoS = v.Photo
            }).ToList();

            return VoitureViewModel != null ?
                        View(VoitureViewModel) :
                        Problem("Entity set 'ApplicationDbContext.Voitures'  is null.");
        }

        // GET: Voitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Voitures == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            var VoitureViewModel = new VoitureViewModel
            {
                IdVoiture = voiture.Id,
                CodeVIN = voiture.CodeVIN,
                DateAchat = voiture.DateAchat,
                Disponible = voiture.Disponible,
                DateVente = voiture.DateVente,
                PrixVente = voiture.PrixVente,
                Description = voiture.Description,
                Annee = voiture.UnModele.Annee,
                Marque = voiture.UnModele.UneMarque.Nom,
                Modele = voiture.UnModele.Nom,
                Finition = voiture.Finition,
                PhotoS = voiture.Photo
            };

            return View(VoitureViewModel);
        }

        // GET: Voitures/Create
        [Authorize (Roles="ADMIN")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create(CreateVoitureViewModel model)
        {
            if (ModelState.IsValid)
            {
                var marque = await _context.Marques
                    .Where(p => p.Nom.ToLower() == model.Marque.ToLower())
                    .FirstOrDefaultAsync();
                if (marque == null)
                {
                    marque = new Marque()
                    {
                        Nom = model.Marque
                    };
                    _context.Add(marque);
                }

                var modele = await _context.Modeles
                    .Where(p => p.Annee == model.Annee && p.Nom.ToLower() == model.Modele.ToLower() && p.UneMarque == marque)
                    .FirstOrDefaultAsync();
                if (modele == null)
                {
                    modele = new Modele()
                    {
                        Annee = model.Annee,
                        Nom = model.Modele,
                        UneMarque = marque
                    };
                    _context.Add(modele);
                }

                await _context.SaveChangesAsync();

                // Définir le dossier de stockage (wwwroot/uploads)
                string uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                // Générer un nom unique pour l'image
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Photo.FileName);
                string filePath = Path.Combine(uploadPath, fileName);

                // Enregistrer l'image sur le serveur
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await model.Photo.CopyToAsync(stream);
                }

                string prixVente = (Convert.ToDouble(model.PrixAchat) + 500).ToString();

                var UneVoiture = new Voiture()
                {
                    PrixAchat = model.PrixAchat,
                    Finition = model.Finition,
                    Photo = fileName,
                    UnModele = modele,
                    PrixVente = prixVente
                };

                _context.Add(UneVoiture);
                await _context.SaveChangesAsync();

                ViewData["Titre"] = "Merci !";
                ViewData["p"] = "votre voiture a été bien publiée";

                return View("Confirmation");
            }

            return View(model);
        }

        // GET: Voitures/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Voitures == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            var VoitureViewModel = new EditVoitureViewModel
            {
                IdVoiture = voiture.Id,
                CodeVIN = voiture.CodeVIN,
                DateAchat = voiture.DateAchat,
                Disponible = voiture.Disponible,
                DateVente = voiture.DateVente,
                PrixVente = voiture.PrixVente,
                PrixAchat = voiture.PrixAchat,
                Description = voiture.Description,
                Annee = voiture.UnModele.Annee,
                Marque = voiture.UnModele.UneMarque.Nom,
                Modele = voiture.UnModele.Nom,
                Finition = voiture.Finition,
                PhotoS = voiture.Photo
            };

            return View(VoitureViewModel);
        }

        // POST: Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(EditVoitureViewModel model, int id)
        {
            if (id != model.IdVoiture)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var marque = await _context.Marques
                        .Where(p => p.Nom.ToLower() == model.Marque.ToLower())
                        .FirstOrDefaultAsync();
                    if (marque == null)
                    {
                        marque = new Marque()
                        {
                            Nom = model.Marque
                        };
                        _context.Add(marque);
                    }

                    var modele = await _context.Modeles
                        .Where(p => p.Annee == model.Annee && p.Nom.ToLower() == model.Modele.ToLower() && p.UneMarque == marque)
                        .FirstOrDefaultAsync();
                    if (modele == null)
                    {
                        modele = new Modele()
                        {
                            Annee = model.Annee,
                            Nom = model.Modele,
                            UneMarque = marque
                        };
                        _context.Add(modele);
                    }

                    await _context.SaveChangesAsync();
                    string fileName = "";
                    var UneVoiture = _context.Voitures.AsNoTracking().FirstOrDefault(v => v.Id == id);
                    if (model.Photo != null)
                    {
                        // Définir le dossier de stockage (wwwroot/uploads)
                        string uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                        // Générer un nom unique pour l'image
                        fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Photo.FileName);
                        string filePath = Path.Combine(uploadPath, fileName);

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Express Voitures</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/41b8d6857f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projet5ApplicationDotNet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Voitures" asp-action="Index">Express Voitures</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voitures" asp-action="Index">Accueil</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.Now.Year - Express Voitures
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>