Models/Voiture.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;

namespace Projet5ApplicationDotNet.Models
{
    public class Voiture
    {
        public int Id {  get; set; }

        public string? CodeVIN { get; set; }

        public string Finition { get; set; }

        public DateTime? DateAchat { get; set; }

        public string PrixAchat { get; set; }

        public bool Disponible { get; set; } = false;

        public DateTime? DateVente { get; set; }

        public string Photo { get; set; }

        public string? Description { get; set; }

        public string? PrixVente { get; set; }

        public Modele UnModele { get; set; }

        public virtual ICollection<Reparation>? ListeReparation { get; set; }
    }
}

Models/VoitureViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace Projet5ApplicationDotNet.Models
{
    public class VoitureViewModel
    {
        public int IdVoiture { get; set; }

        [Display(Name = "Code VIN")]
        public string? CodeVIN { get; set; }

        [Display(Name = "Date d'achat")]
        public DateTime? DateAchat { get; set; }

        [Display(Name = "Prix d'achat")]
        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        public string PrixAchat { get; set; }

        public bool Disponible { get; set; } = false;

        [Display(Name = "Date de vente")]
        public DateTime? DateVente { get; set; }

        [Display(Name = "Prix de vente")]
        public string? PrixVente { get; set; }

        public string? Description { get; set; }

        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        [Range(1990, 2025, ErrorMessage = "L'année doit être comprise entre 1990 et 2025.")]
        [Display(Name = "Année")]
        public int Annee { get; set; }

        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        public string Marque { get; set; }

        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        [Display(Name = "Modèle")]
        public string Modele { get; set; }

        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        public string Finition { get; set; }

        [Required(ErrorMessage = "Veuillez remplir ce champ !")]
        public IFormFile Photo { get; set; }

        [Display(Name = "Photo")]
        public string? PhotoS { get; set; }
    }
}

Controllers/ReparationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet5ApplicationDotNet.Data;
using Projet5ApplicationDotNet.Models;

namespace Projet5ApplicationDotNet.Controllers
{
    [Authorize(Roles = "ADMIN")]
    public class ReparationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReparationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reparations
        public async Task<IActionResult> Liste(int id)
        {
            var reparations = await _context.Reparations.Where(r => r.UneVoiture.Id == id).ToListAsync();

            var ReparationViewModel = new ReparationViewModel();
            HttpContext.Session.SetInt32("IdVoiture", id);

            ReparationViewModel.IdVoiture = id;
            ReparationViewModel.ListeReparation = reparations;

            return ReparationViewModel != null ?
                          View(nameof(Index), ReparationViewModel) :
                          Problem("Entity set 'ApplicationDbContext.Reparations'  is null.");
        }

        // POST: Reparations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReparationViewModel reparation)
        {
            int? IdVoiture = HttpContext.Session.GetInt32("IdVoiture");

            var voiture = await _context.Voitures.FindAsync(IdVoiture);

            var UneReparation = new Reparation()
            {
                Cout = reparation.Cout,
                Commentaire = reparation.Commentaire,
                UneVoiture = voiture
            };

            if (ModelState.IsValid)
            {
                _context.Add(UneReparation);

                voiture.PrixVente = (Convert.ToDouble(voiture.PrixVente) + Convert.ToDouble(reparation.Cout)).ToString();
                _context.Update(voiture);

                await _context.SaveChangesAsync();
                return RedirectToAction("Liste", new {id = IdVoiture });
            }

            var reparations = await _context.Reparations.Where(r => r.UneVoiture.Id == IdVoiture).ToListAsync();

            var ReparationViewModel = new ReparationViewModel()
            {
                Cout = reparation.Cout,
                Commentaire = reparation.Commentaire,
                ListeReparation = reparations,
                IdVoiture = (int)IdVoiture
            };

            return View("Index", ReparationViewModel);
        }

        // GET: Reparations/Delete/5
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            int? IdVoiture = HttpContext.Session.GetInt32("IdVoiture");

            var voiture = await _context.Voitures.FindAsync(IdVoiture);

            if (_context.Reparations == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Reparations'  is null.");
            }

            var reparation = await _context.Reparations.FindAsync(id);
            if (reparation != null)
            {
                voiture.PrixVente = (Convert.ToDouble(voiture.PrixVente) - Convert.ToDouble(reparation.Cout)).ToString();
                _context.Reparations.Remove(reparation);
                _context.Update(voiture);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Liste", new {id = IdVoiture });
        }

        private bool ReparationExists(int id)
        {
          return (_context.Reparations?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/VoituresController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet5ApplicationDotNet.Data;
using Projet5ApplicationDotNet.Models;
using Microsoft.AspNetCore.Authorization;

namespace Projet5ApplicationDotNet.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Voitures
        public async Task<IActionResult> Index()
        {
            // Liste des voitures disponibles pour les visiteurs
            var voitures = await _context.Voitures
                .Where(v => v.Disponible.Equals(true))
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .ToListAsync();

            // Sinon liste de toutes les voitures pour le vendeur
            if (User.IsInRole("ADMIN"))
            { 
                voitures = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .ToListAsync();

            }
            var VoitureViewModel = voitures.Select(v => new VoitureViewModel
            {
                IdVoiture = v.Id,
                CodeVIN = v.CodeVIN,
                DateAchat = v.DateAchat,
                Disponible = v.Disponible,
                DateVente = v.DateVente,
                PrixVente = v.PrixVente,
                Description = v.Description,
                Annee = v.UnModele.Annee,
                Marque = v.UnModele.UneMarque.Nom,
                Modele = v.UnModele.Nom,
                Finition = v.Finition,
                PhotoS = v.Photo
            }).ToList();

            return VoitureViewModel != null ?
                        View(VoitureViewModel) :
                        Problem("Entity set 'ApplicationDbContext.Voitures'  is null.");
        }

        // GET: Voitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Voitures == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            var VoitureViewModel = new VoitureViewModel
            {
                IdVoiture = voiture.Id,
                CodeVIN = voiture.CodeVIN,
                DateAchat = voiture.DateAchat,
                Disponible = voiture.Disponible,
                DateVente = voiture.DateVente,
                PrixVente = voiture.PrixVente,
                Description = voiture.Description,
                Annee = voiture.UnModele.Annee,
                Marque = voiture.UnModele.UneMarque.Nom,
                Modele = voiture.UnModele.Nom,
                Finition = voiture.Finition,
                PhotoS = voiture.Photo
            };

            return View(VoitureViewModel);
        }

        // GET: Voitures/Create
        [Authorize (Roles="ADMIN")]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Create(CreateVoitureViewModel model)
        {
            if (ModelState.IsValid)
            {
                var marque = await _context.Marques
                    .Where(p => p.Nom.ToLower() == model.Marque.ToLower())
                    .FirstOrDefaultAsync();
                if (marque == null)
                {
                    marque = new Marque()
                    {
                        Nom = model.Marque
                    };
                    _context.Add(marque);
                }

                var modele = await _context.Modeles
                    .Where(p => p.Annee == model.Annee && p.Nom.ToLower() == model.Modele.ToLower() && p.UneMarque == marque)
                    .FirstOrDefaultAsync();
                if (modele == null)
                {
                    modele = new Modele()
                    {
                        Annee = model.Annee,
                        Nom = model.Modele,
                        UneMarque = marque
                    };
                    _context.Add(modele);
                }

                await _context.SaveChangesAsync();

                // Définir le dossier de stockage (wwwroot/uploads)
                string uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                // Générer un nom unique pour l'image
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Photo.FileName);
                string filePath = Path.Combine(uploadPath, fileName);

                // Enregistrer l'image sur le serveur
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await model.Photo.CopyToAsync(stream);
                }

                string prixVente = (Convert.ToDouble(model.PrixAchat) + 500).ToString();

                var UneVoiture = new Voiture()
                {
                    PrixAchat = model.PrixAchat,
                    Finition = model.Finition,
                    Photo = fileName,
                    UnModele = modele,
                    PrixVente = prixVente
                };

                _context.Add(UneVoiture);
                await _context.SaveChangesAsync();

                ViewData["Titre"] = "Merci !";
                ViewData["p"] = "votre voiture a été bien publiée";

                return View("Confirmation");
            }

            return View(model);
        }

        // GET: Voitures/Edit/5
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Voitures == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voitures
                .Include(v => v.UnModele)
                .Include(v => v.UnModele.UneMarque)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            var VoitureViewModel = new EditVoitureViewModel
            {
                IdVoiture = voiture.Id,
                CodeVIN = voiture.CodeVIN,
                DateAchat = voiture.DateAchat,
                Disponible = voiture.Disponible,
                DateVente = voiture.DateVente,
                PrixVente = voiture.PrixVente,
                PrixAchat = voiture.PrixAchat,
                Description = voiture.Description,
                Annee = voiture.UnModele.Annee,
                Marque = voiture.UnModele.UneMarque.Nom,
                Modele = voiture.UnModele.Nom,
                Finition = voiture.Finition,
                PhotoS = voiture.Photo
            };

            return View(VoitureViewModel);
        }

        // POST: Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> Edit(EditVoitureViewModel model, int id)
        {
            if (id != model.IdVoiture)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var marque = await _context.Marques
                        .Where(p => p.Nom.ToLower() == model.Marque.ToLower())
                        .FirstOrDefaultAsync();
                    if (marque == null)
                    {
                        marque = new Marque()
                        {
                            Nom = model.Marque
                        };
                        _context.Add(marque);
                    }

                    var modele = await _context.Modeles
                        .Where(p => p.Annee == model.Annee && p.Nom.ToLower() == model.Modele.ToLower() && p.UneMarque == marque)
                        .FirstOrDefaultAsync();
                    if (modele == null)
                    {
                        modele = new Modele()
                        {
                            Annee = model.Annee,
                            Nom = model.Modele,
                            UneMarque = marque
                        };
                        _context.Add(modele);
                    }

                    await _context.SaveChangesAsync();
                    string fileName = "";
                    var UneVoiture = _context.Voitures.AsNoTracking().FirstOrDefault(v => v.Id == id);
                    if (model.Photo != null)
                    {
                        // Définir le dossier de stockage (wwwroot/uploads)
                        string uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                        // Générer un nom unique pour l'image
                        fileName = Guid.NewGuid().ToString() + Path.GetExtension(model.Photo.FileName);
                        string filePath = Path.Combine(uploadPath, fileName);

Views/Voitures/Confirmation.cshtml
@{
    ViewData["Title"] = "Confirmation";
}

<div class="mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 d-flex flex-column">
            <h1 class="fst-italic mt-5 text-center">@ViewData["Titre"]</h1>
            <p class="mb-5 text-center">@ViewData["p"]</p>
            <a asp-action="Index" class="btn bg-D9A963 ft-DM p-3 mt-5 align-self-center">Retour à l'accueil</a>
        </div>
    </div>
</div>

Views/Voitures/Create.cshtml
@model Projet5ApplicationDotNet.Models.CreateVoitureViewModel

@{
    ViewData["Title"] = "Ajouter une voiture";
}

<a asp-action="Index" class="color-796157 text-decoration-none ft-DM"><-- Retour</a>
<h1 class="text-center color-796157 fst-italic">Ajouter une voiture</h1>
<p class="text-center">tous les champs sont obligatoires</p>
<div class="row justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mt-4">
                <label asp-for="PrixAchat" class="control-label mb-3">Prix d'achat</label>
                <input asp-for="PrixAchat" class="form-control p-3 border-1 border-color-2C1810" />
                <span asp-validation-for="PrixAchat" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Annee" class="control-label mb-3">Année</label>
                <input asp-for="Annee" class="form-control p-3 border-1 border-color-2C1810" />
                <span asp-validation-for="Annee" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Marque" class="control-label mb-3">Marque</label>
                <input asp-for="Marque" class="form-control p-3 border-1 border-color-2C1810" />
                <span asp-validation-for="Marque" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Modele" class="control-label mb-3">Modèle</label>
                <input asp-for="Modele" class="form-control p-3 border-1 border-color-2C1810" />
                <span asp-validation-for="Modele" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Finition" class="control-label mb-3">Finition</label>
                <input asp-for="Finition" class="form-control p-3 border-1 border-color-2C1810" />
                <span asp-validation-for="Finition" class="text-danger"></span>
            </div>
            <div class="form-group mt-4">
                <label asp-for="Photo" class="control-label mb-3">Visuel</label>
                <input asp-for="Photo" class="form-control p-5 border-1 border-color-2C1810" type="file" accept="image/*" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group mt-4 d-flex justify-content-center">
                <input type="submit" value="Publier" class="btn bg-D9A963 ft-DM p-3" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Voitures/Delete.cshtml
@model Projet5ApplicationDotNet.Models.VoitureViewModel

@{
    ViewData["Title"] = "Supression";
}

<h1>Supression</h1>

<h3>Etes-vous sûr de vouloir supprimer cette voiture ?</h3>
<div class="mt-5">
    <a asp-action="Index" class="color-796157 text-decoration-none ft-DM"><-- Retour</a>
    <div class="row align-items-center mt-5">
        <div class="col-md-6">
            <img class="w-100" src="~/uploads/@Html.DisplayFor(model => model.PhotoS)" />
        </div>
        <div class="col-md-6">
            <div class="d-flex flex-column justify-content-center">
                <h3 class="color-2C1810 mb-4">@Html.DisplayFor(model => model.PrixVente) €</h3>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Annee)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Marque)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Modele)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Finition)</p>
            </div>
            <div class="mt-5">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="IdVoiture" />
                    <input type="submit" value="Supprimer" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>
@* <div>
    <h4>Voiture</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodeVIN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodeVIN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Finition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Finition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAchat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAchat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrixAchat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrixAchat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disponible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disponible)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateVente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateVente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrixVente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrixVente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div> *@

Views/Voitures/Details.cshtml
@model Projet5ApplicationDotNet.Models.VoitureViewModel
@using Microsoft.AspNetCore.Identity
@using Projet5ApplicationDotNet.Areas.Identity.Data
@inject SignInManager<Projet5ApplicationDotNetUser> SignInManager

@{
    ViewData["Title"] = "Détails";
}

<div class="mt-5">
    <a asp-action="Index" class="color-796157 text-decoration-none ft-DM"><-- Retour</a>
    <div class="row align-items-center mt-5">
        <div class="col-md-6">
            <img class="w-100" src="~/uploads/@Html.DisplayFor(model => model.PhotoS)" />
        </div>
        <div class="col-md-6">
            @if (User.IsInRole("ADMIN"))
            {
                <div class="mb-5">
                    <p class="color-2C1810">Vous avez publié cette annonce, vous pouvez le :</p>
                    <a asp-action="Edit" asp-route-id="@Model?.IdVoiture" class="color-929292 me-4">modifier</a> <a asp-action="Delete" asp-route-id="@Model?.IdVoiture" class="text-danger me-4">supprimer</a> <a asp-action="Liste" asp-controller="Reparations" asp-route-id="@Model?.IdVoiture" class="color-929292">Liste des réparations</a>
                </div>
            }
            <div class="d-flex flex-column justify-content-center">
                <h3 class="color-2C1810 mb-4">@Html.DisplayFor(model => model.PrixVente) €</h3>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Annee)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Marque)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Modele)</p>
                <p class="color-796157 ft-DM">@Html.DisplayFor(model => model.Finition)</p>
            </div>
        </div>
    </div>
</div>

Views/Voitures/Edit.cshtml
@model Projet5ApplicationDotNet.Models.EditVoitureViewModel
@using System.Text.Encodings.Web;

@{
    ViewData["Title"] = "Modifier";
}

<a asp-action="Index" class="color-796157 text-decoration-none ft-DM"><-- Retour</a>
<div class="row mt-5">
    <div class="col-md-12">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdVoiture" />
            <div class="row">
                <div class="col-md-6">
                    <h2><strong>Prix de vente</strong> : @Html.DisplayFor(model => model.PrixVente) €</h2>
                    <img class="w-100" src="~/uploads/@Html.DisplayFor(model => model.PhotoS)" />
                </div>
                <div class="col-md-4 d-flex flex-column">
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="CodeVIN" class="control-label"></label>
                        <input asp-for="CodeVIN" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="CodeVIN" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Finition" class="control-label"></label>
                        <input asp-for="Finition" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="Finition" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Marque" class="control-label"></label>
                        <input asp-for="Marque" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="Marque" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Modele" class="control-label"></label>
                        <input asp-for="Modele" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="Modele" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Annee" class="control-label"></label>
                        <input asp-for="Annee" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="Annee" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="DateAchat" class="control-label"></label>
                        <input asp-for="DateAchat" class="form-control p-3 border-1 border-color-2C1810" type="date" />
                        <span asp-validation-for="DateAchat" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="PrixAchat" class="control-label"></label>
                        <input asp-for="PrixAchat" class="form-control p-3 border-1 border-color-2C1810" />
                        <span asp-validation-for="PrixAchat" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check mb-4 align-self-center">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Disponible" /> @Html.DisplayNameFor(model => model.Disponible)
                        </label>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="DateVente" class="control-label"></label>
                        <input asp-for="DateVente" class="form-control p-3 border-1 border-color-2C1810" type="date" />
                        <span asp-validation-for="DateVente" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Photo" class="control-label"></label>
                        <input asp-for="Photo" class="form-control p-3 border-1 border-color-2C1810" type="file" accept="image/*" />
                        <span asp-validation-for="Photo" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4 align-self-center">
                        <label asp-for="Description" class="control-label"></label>
                        <textarea asp-for="Description" class="form-control p-3 border-1 border-color-2C1810"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group d-flex justify-content-center">
                        <input type="submit" value="Sauvegarder" class="btn bg-D9A963 ft-DM p-3" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}